---
driver:
  name: docker_cli
  require_chef_omnibus: false
  run_command:
    - curl -L https://www.chef.io/chef/install.sh | bash
  publish:
    - 8100:80

transport:
  name: docker_cli

provisioner:
  name: chef_zero

platforms:
  #- name: ubuntu-14.04
  - name: centos-6.7
  - name: toshihirock/amzn-2015.09

  - name: AmazonLinux-20150301
    driver:
      image_id: ami-1c1b9f1c
      name: ec2
      aws_ssh_key_id: ToshihirockKey
      security_group_ids: ["sg-d8df9abd"]
      region: ap-northeast-1
      availability_zone: ap-northeast-1a
      require_chef_omnibus: true
      instance_type: t2.micro
    transport:
      username: ec2-user
      ssh_key: ~/.ssh/ToshihirockKey.pem

suites:
  - name: default
    run_list:
      - recipe[myweb::default]
    attributes:
