---
driver:
  name: docker_cli
  require_chef_omnibus: false
  run_command:
    - curl -L https://www.chef.io/chef/install.sh | bash
  publish:
    - 8100:80

transport:
  name: docker_cli

provisioner:
  name: chef_zero

platforms:
  #- name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[myweb::default]
    attributes:
